info:
    version: 1.0.1
    description: Non-3GPP UE configuration for the generic multi-UPF deployment
configuration:
    N3IWFInformation:
        IPSecIfaceAddr: 10.100.200.240
        IPsecInnerAddr: 10.0.0.1
    N3UEInformation:
        IMSI:
            PLMNID:
                MCC: 208
                MNC: 93
            MSIN: 0000001234
        AMFID: cafe00
        IPSecIfaceName: eth0
        IPSecIfaceAddr: 10.100.200.203
        DnIPAddr:
        XfrmiId: 1
        XfrmiName: ipsec
        GreIfaceName: gretun
        IkeSaSPI: 0x000000000006f708
        IPSecSA3gppControlPlaneSPI: 0x00000002
        SmPolicy:
            - DNN: internet
              SNSSAI:
                SST: 1
                SD: 010203
            - DNN: internet2
              SNSSAI:
                SST: 1
                SD: 112233
        Security:
            K: b73a90cbcf3afb622dba83c58a8415df
            RAND: b120f1c1a0102a2f507dd543de68281f
            SQN: 16f3b3f71005
            AMF: 8000
            OP: b672047e003bb952dca6cb8af0e5b779
            OPC: df0c67868fa25f748b7044c6e7c245b8
logger:
    N3UE:
        debugLevel: trace
        ReportCaller: false
